# Generated by Django 4.2.3 on 2023-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_Password', models.CharField(max_length=100)),
                ('Mobile_No', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PIN', models.CharField(max_length=50)),
            ],
        ),
    ]
