# Generated by Django 4.2.3 on 2023-08-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Register',
        ),
    ]
