# Generated by Django 4.2.3 on 2023-08-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0003_rename_signup_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='product/')),
                ('product_price', models.IntegerField()),
                ('product_oprice', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_dprice', models.IntegerField()),
                ('product_description', models.TextField()),
                ('product_gst', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('added_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
    ]
