# Generated by Django 4.2.3 on 2023-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0004_product_delete_log_rename_email_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('status', models.IntegerField()),
                ('added_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='name',
        ),
    ]
