# Generated by Django 4.2.3 on 2023-08-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0005_cart_rename_name_register_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_on',
        ),
    ]
