# Generated by Django 4.2.3 on 2023-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0006_remove_cart_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
