# Generated by Django 4.2.3 on 2023-08-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Luxuria', '0007_cart_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
